In [10]:
import numpy as np

a = np.array([1,2,3]) # 벡터
b = np.array([[1,2,3],[4,5,6],[5,6,7]]) # 3x3 행렬
c = np.array([[1,2],[2,3]])

print(a)
print(b)
print(c)

[1 2 3]
[[1 2 3]
 [4 5 6]
 [5 6 7]]
[[1 2]
 [2 3]]


In [33]:
print(a.ndim) # 차원을 보여줌 1=벡터 2=행렬
print(b.ndim,'\n')

print(a.shape) # 3, -> 3,1
print(b.shape,'\n')

print(a.size) # 스칼라가 몇 개 있는지 (원소가 몇개인지)
print(b.size)

1
2 

(3,)
(3, 3) 

3
9


In [20]:
x = np.zeros((3,2)) # float 타입으로 만들어짐
y = np.ones((3,4)) # float 타입으로 만들어짐
z = np.full((2,3), 5) # 5로 가득찬 2x3행렬, int 타입으로 만들어짐

print(x,'\n')
print(y, '\n')
print(z)

[[0. 0.]
 [0. 0.]
 [0. 0.]] 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

[[5 5 5]
 [5 5 5]]


In [30]:
# np.arange
x = np.arange(0,10)
x2 = np.arange(0, 10, 2)
print(x)
print(x2)

# np.linspace(초기값, 끝나는값(포함), 개수)
y = np.linspace(0, 10, 5)

print(y)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]


In [44]:
a = np.arange(0,10)
print(a,'\n')

b = a.reshape(5,2) # -1로 넣으면 가변적이라는 뜻 즉, 2x5 가 됨 순서가 중요함!
print(b)

[0 1 2 3 4 5 6 7 8 9] 

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [54]:
# b[행,렬]
print(b,'\n')
print(b[0,0])
print(b[4,1],'\n')
print(b[:,1],'\n') # 모든행, 첫번째 열
print(b[1,:])
print(b[2:5])


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] 

0
9 

[1 3 5 7 9] 

[2 3]
[[4 5]
 [6 7]
 [8 9]]


In [75]:
c = np.arange(0,12)
c = c.reshape(4,3)
print(c,'\n')

# c[시작지점:끝지점(포함)]
print(c[1:4],'\n') 
print(c[2,2:],'\n')
print(c[0,1:],'\n')
print(c[2:,1],'\n')

print(c[:2, 1],'\n')
print(c[1:3,2:],'\n')
print(c[1:,1:],'\n')

print(c[-1,-1],'\n')
print(c[1:,1:-1],'\n') # 1번째 행부터 끝까지, 1번째열부터 맨마지막은 빼고
print(c[-4,-3],'\n')

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

[8] 

[1 2] 

[ 7 10] 

[1 4] 

[[5]
 [8]] 

[[ 4  5]
 [ 7  8]
 [10 11]] 

11 

[[ 4]
 [ 7]
 [10]] 

0
