# 1번 문제

In [17]:
import numpy as np
import numpy.matlib
import matplotlib.pyplot as plt
from scipy.stats import multivariate_normal

X = np.genfromtxt('wine-clustering.csv', delimiter=',', skip_header = 1)

Xmin = np.min(X, axis = 0)
Xmax = np.max(X, axis = 0)
X = (X - Xmin) / Xmax

(N,D) = X.shape

In [18]:
print(X.shape)
print(N, D) # 샘플의 개수, 차원 (178개 13차원의 벡터)
print(X)

(178, 13)
178 13
[[0.21577883 0.16724138 0.33126935 ... 0.32748538 0.6625     0.46845238]
 [0.14632502 0.17931034 0.24148607 ... 0.33333333 0.5325     0.45952381]
 [0.14362778 0.27931034 0.40557276 ... 0.32163743 0.475      0.53988095]
 ...
 [0.15104518 0.61034483 0.27863777 ... 0.06432749 0.0725     0.33154762]
 [0.14430209 0.31896552 0.3126935  ... 0.07017544 0.0875     0.33452381]
 [0.20903574 0.57931034 0.42724458 ... 0.07602339 0.0825     0.16785714]]


In [ ]:
def train_kmeans(X, mu_init, maxIter):
    K=2
    # n번째 sample부터, k번째 cluster의 중심까지의 거리**2
    labels = np.zeros((N,K), dtype = bool) # 178,2

    c = np.argmin(dist2, axis = 1)
    labels = np.zeros((N,K), dtype = bool)
    labels[np.arange(N),c] = 1
    for iter in range(0,10):
        for k in range(0,K):
            labels[:,k] = np.sum((X - np.matlib.repmat(mu_init[k,:],N,1))**2, axis = 1)
            #X -> 178,13
            #np.matlib.repmat(mu_init[k,:],N,1) -> 178,2 

        # 어느 cluster까지 제일 가까운지를 c에 저장
        c = np.argmin(labels, axis = 1) # dist = (N x K), 
        
        # 각 cluster에 대해 mu를 업데이트
        for k in range(0,K):
            mu_init[k,:] = np.mean(X[c == k,:], axis = 0)
    print(labels)
    #return labels

In [ ]:
mu_init = np.hstack([0.2*np.ones((13,1)), 0.6*np.ones((13,1))])# 0.2, 0.6 
maxIter = 20


label1 = train_kmeans(X, mu_init, maxIter)


In [ ]:
plt.figure(figsize = (15, 15))

for i in range(0, D):
    for j in range(0, D):
        plt.subplot(D, D, (i + 1) + D*j)
        for k in range(0,2):
            plt.plot(X[label1 == k,i],X[label1 == k,j],".",markersize = 5)

In [ ]:
a = np.matlib.repmat(mu_init[2,:],178,1)
print(a.shape)
#print(mu_init)
#print(mu_init.shape)


In [ ]:
print(mu_init.shape)

In [ ]:
def train_MoG(X, mu_init, maxIter):
    return labels

In [ ]:
mu_init = np.hstack([0.2*np.ones((13,1)), 0.6*np.ones((13,1))])# 0.2, 0.6 
maxIter = 20

label1 = train_kmeans(X, mu_init, maxIter)
label2 = train_MoG(X, mu_init, maxIter)

plt.figure(figsize = (15, 15))

for i in range(0, D):
    for j in range(0, D):
        plt.subplot(D, D, (i + 1) + D*j)
        for k in range(0,2):
            plt.plot(X[label1 == k,i],X[label1 == k,j],".",markersize = 5)

plt.figure(figsize = (15, 15))

for i in range(0, D):
    for j in range(0, D):
        plt.subplot(D, D, (i + 1) + D*j)
        for k in range(0,2):
            plt.plot(X[label2 == k,i],X[label2 == k,j],".",markersize = 5)